name: test-linux

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:


jobs:
  unicode-icu:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: install dependencies
        run: |
            sudo apt-get update ||:
            sudo apt-get -y install build-essential  libtest-pod-coverage-perl libtest-pod-perl libpod-parser-perl libpod-spell-perl aspell libicu-dev
      - name: checkout
        uses: actions/checkout@v2
      - name: configure
        run: |
            cd Collator && perl Makefile.PL
      - name: build
        run: |
            cd Collator && make
      - name: test
        run: |
            cd Collator && AUTOMATED_TESTING=1 make test
